apiVersion: v2
name: kyverno
description: A Helm chart for installing Kyverno with policies
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: kyverno
    version: 3.2.6
    repository: https://kyverno.github.io/kyverno/
